Update script for Slack 15.0, bump version to 0.19.1

diff --git a/elinks.SlackBuild b/elinks.SlackBuild
--- a/elinks.SlackBuild
+++ b/elinks.SlackBuild
@@ -1,7 +1,7 @@
 #!/bin/sh
 #
 # Slackware build script for ELinks
-# Copyright (C) 2016-2020 Georgi D. Sotirov <gdsotirov@gmail.com>
+# Copyright (C) 2016-2026 Georgi D. Sotirov <gdsotirov@dir.bg>
 #
 # This program is free software; you can redistribute it and/or
 # modify it under the terms of the GNU General Public License
@@ -12,18 +12,18 @@
 # but WITHOUT ANY WARRANTY; without even the implied warranty of
 # MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 # GNU General Public License for more details.
-#
+# 
 # You should have received a copy of the GNU General Public License
 # along with this program; if not, write to the Free Software
 # Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 #
-# Visit SlackPack at https://sotirov-bg.net/slackpack/
+# Visit SlackPack at http://sotirov-bg.net/slackpack/
 #
 
 . ../../slack-package.conf
 
 NAME=elinks
-VERSION=0.13.20160821
+VERSION=0.19.1
 ARCH=${ARCH:-i586}
 BUILD=${BUILD:-1}
 
@@ -31,12 +31,12 @@ TMP=${TMP:-/tmp}
 CWD=${CWD:-`pwd`}
 
 if [ ! -e $TMP ]; then
-  mkdir -p $TMP # location to build the source
+  mkdir --parents $TMP # location to build the source
 fi
 
 SRC=$TMP/${NAME}-${VERSION}
 if [ -e $SRC -a -d $SRC ]; then
-  echo "Source directory '$SRC' already exists! Plaese, move it or remove it."
+  echo "Source directory '$SRC' already exists! Please, move it or remove it."
   exit 1
 fi
 
@@ -45,78 +45,84 @@ if [ -e $PKG -a -d $PKG ]; then
   echo "Package creation directory '$PKG' already exists! Please, move it or remove it."
   exit 2
 fi
-mkdir -p $PKG
+mkdir --parents $PKG
 
 # Get, backup and fix source
 cd $TMP
-tar -xvf $CWD/${NAME}-${VERSION}.tar.?z* || exit 3
+tar --extract --verbose --file=$CWD/${NAME}-${VERSION}.tar.xz || exit 3
 cd $SRC
 fix_source
 
 if [ -e $CWD/${NAME}-${VERSION}.diff ]; then
-  patch -p1 -b -z.orig < $CWD/${NAME}-${VERSION}.diff || exit 4
+  patch --backup --strip=1 --suffix=.orig < $CWD/${NAME}-${VERSION}.diff || exit 4
 fi
 
 # Configure
 ./autogen.sh || exit 50
 CFLAGS="$SLKCFLAGS" \
 CPPFLAGS="$SLKCFLAGS" \
-./configure --build=${ARCH}-slackware-linux \
-            --host=${ARCH}-slackware-linux \
-            --prefix=/usr \
-            --mandir=/usr/man \
-            --enable-largefile \
-            --enable-bookmarks \
-            --enable-xbel \
-            --enable-nls \
-            --enable-cookies \
-            --enable-formhist \
-            --enable-globhist \
-            --enable-mailcap \
-            --enable-mimetypes \
-            --enable-ipv6 \
-            --enable-bittorrent \
-            --enable-data \
-            --enable-uri-rewrite \
-            --enable-cgi \
-            --enable-finger \
-            --enable-ftp \
-            --enable-gopher \
-            --enable-nntp \
-            --enable-smb \
-            --enable-mouse \
-            --enable-88-colors \
+./configure --build="${ARCH}-slackware-linux" \
+            --host="${ARCH}-slackware-linux" \
             --enable-256-colors \
-            --enable-true-color \
-            --enable-exmode \
-            --enable-leds \
-            --enable-marks \
-            --enable-css \
-            --enable-html-highlight \
+            --enable-88-colors \
             --enable-backtrace \
+            --enable-bittorrent \
+            --enable-bookmarks \
+            --enable-cgi \
+            --enable-codepoint \
+            --enable-cookies \
+            --enable-css \
+            --enable-data \
+            --enable-dgi \
+            --enable-exmode \
+            --enable-fastmem \
+            --enable-finger \
+            --enable-formhist \
+            --enable-ftp \
+            --enable-gemini \
+            --enable-gettext \
+            --enable-globhist \
+            --enable-gopher \
+            --enable-html-highlight \
+            --enable-ipv6 \
+            --enable-largefile \
+            --enable-leds \
+            --enable-mailcap \
+            --enable-marks \
+            --enable-mimetypes \
+            --enable-mouse \
+            --enable-nls \
+            --enable-nntp \
+            --enable-sftp \
+            --enable-sm-scripting \
+            --enable-true-color \
+            --enable-uri-rewrite \
             --enable-utf-8 \
-            --with-gpm \
-            --with-zlib \
+            --enable-xbel \
+            --mandir=/usr/man \
+            --prefix=/usr \
+            --with-brotli \
             --with-bzlib \
-            --with-idn \
+            --with-gnutls \
+            --with-gssapi \
+            --with-gpm \
+            --with-idn2 \
+            --with-libcurl \
+            --with-libevent \
+            --with-libiconv \
             --with-lzma \
-            --with-spidermonkey \
-            --with-guile \
+            --with-openssl \
             --with-perl \
             --with-python \
-            --with-lua \
             --with-ruby \
-            --with-gnutls \
-            --with-openssl \
+            --with-terminfo \
+            --with-spidermonkey \
             --with-x \
-            --with-libiconv || exit 5
-
-#           --sable-sm-scripting # requires SpiderMonkey
-#           --with-lzma          # many compilation errors
-#           --with-gssapi        # no kerberos
+            --with-zlib \
+            --with-zstd || exit 5
 
 # Build & install
-make V=1 -j4 || exit 6
+make V=1 --jobs 8 || exit 6
 make V=1 DESTDIR=$PKG install || exit 7
 
 # Prepare
@@ -125,29 +131,30 @@ bin_perms $PKG
 ( cd $SRC; create_docs $PKG ${NAME}-${VERSION} )
 gzip_man $PKG
 
-mkdir -p $PKG/install
-install -m 644 $CWD/slack-desc     $PKG/install/slack-desc
-install -m 644 $CWD/slack-required $PKG/install/slack-required
+install --mode 755 --directory $PKG/install
+install --mode 644 --preserve-timestamps $CWD/slack-desc      $PKG/install/slack-desc
+install --mode 644 --preserve-timestamps $CWD/slack-required  $PKG/install/slack-required
 
 SBDIR=$PKG/usr/src/slackbuilds/${NAME}-${VERSION}
-mkdir -p $SBDIR
-install -m 644 $CWD/slack-desc          $SBDIR/slack-desc
-install -m 644 $CWD/slack-required      $SBDIR/slack-required
+install --mode 755 --directory $SBDIR
+install --mode 644 --preserve-timestamps $CWD/slack-desc      $SBDIR/slack-desc
+install --mode 644 --preserve-timestamps $CWD/slack-required  $SBDIR/slack-required
 if [ -e $CWD/${NAME}-${VERSION}.diff ]; then
-  install -m 644 $CWD/${NAME}-${VERSION}.diff $SBDIR/${NAME}-${VERSION}.diff
+  install --mode 644 --preserve-timestamps $CWD/${NAME}-${VERSION}.diff $SBDIR/${NAME}-${VERSION}.diff
 fi
-install -m 644 $CWD/${NAME}.SlackBuild $SBDIR/${NAME}.SlackBuild
+install --mode 644 --preserve-timestamps $CWD/${NAME}.SlackBuild $SBDIR/${NAME}.SlackBuild
 
-# Assemble
+# Pack
 cd $PKG
 PKGNAME=${NAME}-${VERSION}-${ARCH}-${BUILD}${MYIN}
-makepkg -l y -c n $PKG_DIR/${PKGNAME}.txz
-cd $PKG_DIR
-md5sum ${PKGNAME}.txz > ${PKGNAME}.txz.md5
-cat $PKG/install/slack-desc > $PKG_DIR/${PKGNAME}.txt
+makepkg --chown n --linkadd y --prepend $PKG_DIR/${PKGNAME}.txz
+md5sum $PKG_DIR/${PKGNAME}.txz > $PKG_DIR/${PKGNAME}.txz.md5
+install --mode 644 $PKG/install/slack-desc $PKG_DIR/${PKGNAME}.txt
 
+# Clean Up
 if [ "$1" == "--cleanup" ]; then
-  rm -r $SRC
-  rm -r $PKG
+  rm --recursive $SRC
+  rm --recursive $PKG
 fi
+
 
